-- Fale Confiante
-- Execute este ficheiro no SQL Editor do Supabase quando a base de dados estiver ligada.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  current_day integer not null default 1 check (current_day between 1 and 30),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.lesson_progress (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  lesson_day integer not null check (lesson_day between 1 and 30),
  completed_at timestamptz not null default now(),
  unique (user_id, lesson_day)
);

create table if not exists public.training_sessions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  lesson_day integer not null check (lesson_day between 1 and 30),
  duration_seconds integer not null default 0 check (duration_seconds >= 0),
  score integer check (score between 0 and 100),
  clarity integer check (clarity between 0 and 100),
  pace integer check (pace between 0 and 100),
  confidence integer check (confidence between 0 and 100),
  pauses integer check (pauses between 0 and 100),
  feedback text,
  analysis_source text not null default 'demo',
  created_at timestamptz not null default now()
);

create table if not exists public.coach_messages (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null check (role in ('user', 'assistant')),
  content text not null,
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.lesson_progress enable row level security;
alter table public.training_sessions enable row level security;
alter table public.coach_messages enable row level security;

drop policy if exists "profiles own rows" on public.profiles;
create policy "profiles own rows" on public.profiles for all using (auth.uid() = id) with check (auth.uid() = id);

drop policy if exists "lesson progress own rows" on public.lesson_progress;
create policy "lesson progress own rows" on public.lesson_progress for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "training sessions own rows" on public.training_sessions;
create policy "training sessions own rows" on public.training_sessions for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "coach messages own rows" on public.coach_messages;
create policy "coach messages own rows" on public.coach_messages for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, full_name)
  values (new.id, coalesce(new.raw_user_meta_data ->> 'full_name', ''))
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
